package gui;

import CYT_model.Port;
import Vehicle.AGV;
import apron.Berth;
import apron.QuayCrane;
import javax.swing.table.DefaultTableModel;
import parameter.OutputParameters;
import storageblock.YardCrane;

public class OutputGUI extends javax.swing.JFrame {
    private static Port port;
    
    /** Creates new form Antenna */
    public OutputGUI() {
        initComponents();
        port = CYTMainGUI.port;
        this.setAllInputData();
        this.setShipArrivingData();
        //this.setCurrentOutputList();
        this.setAGVInfo();
        this.setYCInfo();
        super.setTitle("输出窗口_陈禹廷");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllInput = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllOutput = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        AGVInfo = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        YCInfo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        shipArrivingTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OutputPanel");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        AllInput.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(AllInput);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("输入参数", jPanel1);

        AllOutput.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        AllOutput.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(AllOutput);

        AGVInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        AGVInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(AGVInfo);

        YCInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        YCInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(YCInfo);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("实时输出", jPanel2);

        shipArrivingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(shipArrivingTable);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .add(17, 17, 17))
        );

        jTabbedPane1.addTab("到港船舶信息", jPanel3);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 582, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 315, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("结果分析", jPanel4);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        CYTMainGUI.outputGUI = null;
    }//GEN-LAST:event_formWindowClosed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(this.jTabbedPane1.getSelectedIndex() == 2){
            this.setCurrentOutputList();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public static void outputGUIMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AGVInfo;
    private javax.swing.JList<String> AllInput;
    private javax.swing.JList<String> AllOutput;
    private javax.swing.JTable YCInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable shipArrivingTable;
    // End of variables declaration//GEN-END:variables

    private void setAllInputData() {
        String[] inData = new String[6];
        int i = 0;        
        //码头基本信息：
        inData[i++] = "AGV总数:\t"+port.getAGVs().length;
        inData[i++] = "QC总数：\t"+port.getQuayCranes().length;
        inData[i++] = "YC总数：\t"+port.getYardCranes().length;
        inData[i++] = "AGV伴侣：\t"+port.getYards().length*port.getYards()[0].getBlock().length*2;
        inData[i++] = "泊位总长度：\t"+port.getTotalLength();
        inData[i++] = "BlockNum：\t"+port.getYards()[0].getBlock().length+"/Yard";
        //设备参数：---速度等;
        AllInput.setListData(inData);
    }
    protected void setCurrentOutputList() {
        String[] inData = new String[80];
        int i = 0;        
        inData[i++] = "堆场堆箱量：\t"+port.getCNUM();
        inData[i++] = "";
        inData[i] = "Berth状态:";
        for (Berth berth : port.getBerths()) {
            i++;
            inData[i] = berth.getName();
            switch(berth.getBerthState()){
                case -1:
                    inData[i] += "泊位已被分配,等待船舶靠泊";
                    break;
                case 0:
                    inData[i] += "船舶在泊,等待装卸";
                    break;
                case 1:
                    inData[i] += berth.getShip().toString()+"船舶在泊，正在装卸";
                    break;
                case 2:
                    inData[i] += berth.getShip().toString()+"船舶结束装卸";
                    break;
                case 3:
                    inData[i] += "船舶离开";
                    break;
                case 4:
                    inData[i] += "泊位空闲";
                    break;
                default:
                    inData[i] += "NULL";
            }
            inData[i] += "   ";
        }
        AllOutput.setListData(inData);
    }

    private void setShipArrivingData() {
        String[] name = {"编号","计划到港时间(min)","DWT"};
        DefaultTableModel table = new DefaultTableModel(OutputParameters.getShipArrivingList(), name);
        this.shipArrivingTable.setModel(table);
    }

    protected void update() {
        switch(this.jTabbedPane1.getSelectedIndex()){
            case 0:
                //输入信息;
                //this.setAllInputData();
                break;
            case 1:
                //实时输出信息;
                this.setCurrentOutputList();
                this.updateAGVInfo();
                this.updateYCInfo();
                break;
            case 2:
                //船舶到港信息;
                //this.setShipArrivingData(); 
                break;
            case 3:
                //输出分析;
        }
    }

    private void setAGVInfo() {
        String[] name = {"AGV编号","服务岸桥","状态"};
        String[][] agvS = new String[port.getAGVs().length][3];
        int num = 0;
        for (QuayCrane quayCrane : port.getQuayCranes()) {
            for (AGV agv : quayCrane.getServiceAGV()) {
                agvS[num][0] = ""+num;
                agvS[num][1] = ""+agv.getServiceQC().getName();
                agvS[num][2] = ""+agv.getAGVstate();
                num++;
            }
        }
        DefaultTableModel table = new DefaultTableModel(agvS, name);
        this.AGVInfo.setModel(table);
    }
    private void updateAGVInfo() {
        int num = 0;
        for (QuayCrane quayCrane : port.getQuayCranes()) {
            for (AGV agv : quayCrane.getServiceAGV()) {
                this.AGVInfo.getModel().setValueAt(agv.getAGVstate(),num,2);
                num++;
            }
        }
    }
    private void setYCInfo() {
        String[] name = {"场桥所在堆场","场桥位置","任务"};
        String[][] agvS = new String[port.getAGVs().length][3];
        int num = 0;
        for (YardCrane yc : port.getYardCranes()) {
            agvS[num][0] = "" + yc.getYard().getAreaNum()+"Block"+yc.getYardBlock().getLine();
            agvS[num][1] = "["+yc.currentPosition.getX()+","+yc.currentPosition.getY()+"]";
            agvS[num][2] = "" + "";
            num++;
        }
        DefaultTableModel table = new DefaultTableModel(agvS, name);
        this.YCInfo.setModel(table);
    }
    private void updateYCInfo() {
        int num = 0;
        for (YardCrane yc : port.getYardCranes()) {
            this.YCInfo.getModel().setValueAt("["+yc.currentPosition.getX()+","+yc.currentPosition.getY()+"]",num,1);  
            if(yc.isFree() == false){
              this.YCInfo.getModel().setValueAt(yc.getWorkType(),num,2);  
            }
            num++;
        }
    }
}
